export const data = [
  {
    id: "1",
    availability: "Exciting",
    image: "/skydiving.png",
    rating: "5.0",
    counter: "26",
    location: "New Zealand",
    title: "Skydiving with a view",
    price: "$269",
  },
  {
    id: "2",
    availability: "Trending",
    image: "/louvre.png",
    rating: "4.9",
    counter: "58",
    location: "Paris, France",
    title: "Visit Louvre Museum",
    price: "€17",
  },
  {
    id: "3",
    availability: "Seasonal",
    image: "/mountain-biking.png",
    rating: "4.8",
    counter: "2",
    location: "USA",
    title: "Group Mountain Biking",
    price: "$50",
  },
  {
    id: "4",
    availability: "Online",
    image: "/wedding.png",
    rating: "4.6",
    counter: "30",
    location: "London, UK",
    title: "Learn wedding photography",
    price: "£125",
  },
  {
    id: "5",
    availability: "Sold out",
    image: "/katie.png",
    rating: "5.0",
    counter: "6",
    location: "USA",
    title: "Life lessons with Katie Zaferes",
    price: "$136",
  },
];
